Repository johndpjr/AgTern, pull requests merged in 2022-10, with the labels that each got.

#40 Fix PyCharm Run Configurations and add PEP8 Style Checking
  .idea/AgTern.iml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/runConfigurations/AgTern.xml
  .idea/runConfigurations/AgTern__No_Scrape_.xml
  .idea/runConfigurations/AgTern__Show_Scraper_.xml
  .idea/runConfigurations/AgTern__Update_Companies_.xml
Labels: enhancement

#42 Display internships with null period/year correctly
  agtern/gui/frames/internship_list_frame.py
  data/config.ini
Labels: bug

#41 Org/32/Add logger
  .gitignore
  agtern/__main__.py
  agtern/gui/frames/internship_detail_frame.py
  agtern/gui/frames/internship_list_frame.py
  agtern/gui/frames/profile_frame.py
  agtern/gui/frames/top_bar_frame.py
  agtern/logger.py
  agtern/pipelines/backend/scraper.py
  agtern/pipelines/utils/import_companies.py
Labels: feature

#55 gui/46/new search function
  agtern/gui/application.py
  agtern/gui/assets/link-icon.png
  agtern/gui/frames/__init__.py
  agtern/gui/frames/internship_detail_frame.py
  agtern/gui/frames/internship_list_frame.py
  agtern/gui/frames/internship_search_frame.py
  agtern/gui/frames/profile_frame.py
  agtern/gui/frames/top_bar_frame.py
  data/config.ini
  data/db.json
Labels: enhancement, feature, gui
